# Spell checking using CSpell (cspell-action)
# Link: https://github.com/marketplace/actions/cspell-action
# 
# See the ./config/cspell/ directory for information regarding 
# this workflow and the cspell configuration file.
---
name: Spell Check with CSpell
on:
  pull_request:

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false # We don't need the token in subsequent steps

      # Installation required for some dictionaries
      # Import in the .config/cspell/cspell.json file is also required
      - name: Install CSpell Swedish Dictionary
        run: npm install --no-save @cspell/dict-sv @cspell/dict-people-names

      - name: Run CSpell
        uses: streetsidesoftware/cspell-action@v8
        with: # See link at top of file for more configuration options
          files: '' # All files (default)
          config: '.config/cspell/cspell-config.yaml' # Custom cspell config file
          inline: error # Show spelling issues as inline errors in PR
          suggestions: true # Show suggestions for misspelled words
          strict: true # Fail action if any misspelled words (default)
          incremental_files_only: true # Only spell check PR diff (default)
