# Spell checking using Cspell (cspell-action)
# Link: https://github.com/marketplace/actions/cspell-action

# ----- Test -----
# 
# Should pass: 
# - SciLifeLab
# - correct
# - behaviour
# - svenska
# - partman
# - bytea
# - jsquery
# - ZSON
# - acetylcholinesterase
# 
# Should fail: 
# - scilifelab (case sensitive)
# - icorrect (misspelled)
# - fdfsdfsd (nonsense word)
# - behavior (US)
# - organize (US)
# - ssvenska (misspelled Swedish)
---
name: Spell Check
on:
  pull_request:

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false # We don't need the token in subsequent steps

      # Required for Swedish spell-check to work,
      # and keep British English spellings more consistent 
      # (en-GB flags fewer US spellings)
      - name: Install CSpell Dictionaries (en-gb and Swedish)
        run: npm install --no-save @cspell/dict-sv # @cspell/dict-en-gb

      - name: Run CSpell
        uses: streetsidesoftware/cspell-action@v8
        with: # See link in the top for more configuration options
          files: '' # All files (default)
          config: '.config/cspell.json' # Custom cspell config file (default is in root)
          inline: error # Show spelling issues as inline errors in PR (default is warning)
          suggestions: true # Show suggestions for misspelled words (default is false)
          strict: true # Fail action is any misspelled words (default)
          incremental_files_only: true # Only spell check PR diff (default)
