# Spell checking using Cspell (cspell-action)
# Link: https://github.com/marketplace/actions/cspell-action

# ----- Test -----
# 
# Should pass: 
# - SciLifeLab
# - correct
# - behaviour
# - svenska
# 
# Should fail: 
# - scilifelab (case sensitive)
# - icorrect (misspelled)
# - fdfsdfsd (nonsense word)
# - behavior (US)
# - organize (US)
# - ssvenska (misspelled Swedish)
---
name: Spell Check
on:
  pull_request:

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false # default is true, but we don't need it for this action
      
      - name: Install CSpell Dictionaries (en-GB and Swedish)
        run: npm install --no-save @cspell/dict-en-gb @cspell/dict-sv

      - name: Run CSpell
        uses: streetsidesoftware/cspell-action@v8
        with: # See link in the top for more configuration options
          files: '' # Spell check all files (default)
          config: '.config/cspell.json' # Where to find the cspell configuration file cspell.json (default)
          inline: warning # Show spelling issues as warning annotations in the PR (default)
          suggestions: true # Show suggestions for misspelled words
          strict: true # Fail the action if any misspelled words are found (default)
          incremental_files_only: true # Only spell check files that have changed in the PR (default)
