# Validate the Renovate configuration in .config/renovate/
---
name: Validate Renovate config

on:
  pull_request:
    paths:
      - '.config/renovate/**'
      - '.github/renovate.jsonc'

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false # We don't need the token in subsequent steps
      
      - name: Validate preset
        # Our version currently doesn't validate jsonc -- copy to json5
        # Pin 43 to match instance, but not exact version
        # --yes to automatically install renovate-config-validator if not present
        # --no-global because we are validating a shared config preset
        # --strict to fail if scanned config needs migration
        run: |
          cp .config/renovate/default.jsonc "$RUNNER_TEMP/preset.json5"
          npx --yes --package renovate@43 -- \
            renovate-config-validator --no-global --strict "$RUNNER_TEMP/preset.json5"
